<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <AssemblyName>Plugin_Regedit</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sccmclictrlib\sccmclictr.automation\sccmclictr.automation.csproj" />
    <ProjectReference Include="..\..\Customization\Customization.csproj" />
  </ItemGroup>

  

  <ItemGroup>
    <None Remove="Images\**\*" />
    <Resource Include="Images\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
